# Generated by Django 6.1.1 on 2026-09-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Mostrar este médico entre los destacados en la página principal.'),
        ),
        migrations.AddField(
            model_name='medico',
            name='orden_destacado',
            field=models.PositiveIntegerField(default=0, help_text='Menor número = mayor prioridad entre los destacados.'),
        ),
    ]
