# Generated by Django 6.1.1 on 2026-09-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_medico_destacado_medico_orden_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoSobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='sobre_nosotros/')),
                ('texto_alternativo', models.CharField(blank=True, max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Foto de Sobre Nosotros',
                'verbose_name_plural': 'Fotos de Sobre Nosotros',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
