# Generated by Django 6.1.1 on 2026-09-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_fotosobrenosotros'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
    ]
