# Generated by Django 6.1.1 on 2026-09-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_medico_slug'),
        ('servicios', '0004_areaservicio_destacado_areaservicio_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='medicos', to='servicios.servicio', verbose_name='Servicios que realiza'),
        ),
    ]
