# Generated by Django 6.1.1 on 2026-09-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(default='SOBRE NOSOTROS', max_length=100)),
                ('titulo', models.CharField(default='Una clínica comprometida con tu bienestar', max_length=200)),
                ('parrafo_1', models.TextField(default='En Clínica Cruz Jiminian creemos que una buena atención médica comienza escuchando a nuestros pacientes.')),
                ('parrafo_2', models.TextField(default='Nuestro equipo trabaja para ofrecer servicios médicos de calidad en un ambiente profesional, seguro y humano.')),
                ('caracteristica_1_titulo', models.CharField(default='Atención humana', max_length=100)),
                ('caracteristica_1_descripcion', models.CharField(default='Tratamos a cada paciente con respeto y empatía.', max_length=200)),
                ('caracteristica_2_titulo', models.CharField(default='Profesionales capacitados', max_length=100)),
                ('caracteristica_2_descripcion', models.CharField(default='Un equipo comprometido con tu salud.', max_length=200)),
                ('tarjeta_titulo', models.CharField(default='Compromiso', max_length=100)),
                ('tarjeta_subtitulo', models.CharField(default='con tu bienestar', max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Sobre Nosotros',
                'verbose_name_plural': 'Configuración de Sobre Nosotros',
            },
        ),
    ]
