# Generated by Django 6.1.1 on 2026-09-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clinica', models.CharField(default='Clínica Cruz Jiminian', max_length=150)),
                ('logo_header', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
