# Generated by Django 6.1.1 on 2026-09-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_areaservicio_servicio_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaservicio',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Mostrar esta área como tarjeta en la página de inicio.'),
        ),
        migrations.AddField(
            model_name='areaservicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='areas_servicios/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ejemplo: 20-30 minutos', max_length=100),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='preparacion',
            field=models.TextField(blank=True, help_text='Indicaciones que debe seguir el paciente antes del estudio.'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='requiere_cita',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='areaservicio',
            name='icono',
            field=models.CharField(blank=True, help_text='Clase, emoji o identificador del icono', max_length=50),
        ),
    ]
