# Generated by Django 6.1.1 on 2026-09-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('medicos', '0002_medico_destacado_medico_orden_destacado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cita',
            name='cita_medico_fecha_hora_unica',
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'confirmada'])), fields=('medico', 'fecha', 'hora'), name='cita_medico_fecha_hora_activa_unica'),
        ),
    ]
