# Generated by Django 6.1.1 on 2026-09-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_remove_cita_cita_medico_fecha_hora_unica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='numero_cita',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
